### ISSUE TITLE
Recognising Traffic Signs With 98% Accuracy Using Deep Learning

### ISSUE THREAD

**Issue by vincentporte** [IALeMans/24hcode2019#2]
https://towardsdatascience.com/recognizing-traffic-signs-with-over-98-accuracy-using-deep-learning-86737aedc2ab

**Comment by AMairesse** [comment]
Celui-ci semble mieux : https://github.com/georgesung/ssd_tensorflow_traffic_sign_detection
Le modèle n'est pas parfait d'après le descriptif mais semble suffisant et il y a des modèles pré-entrainés.
Je me lance dans une fonction encapsulée pour le faire.

**Comment by AMairesse** [comment]
Done !
Il reste juste à améliorer le modèle pré-entrainé avec plus de data et reprendre le training
Possible aussi de tester avec un inception pour être plus performant
